config/routes.rb
Rails.application.routes.draw do
  resources :gardens, only: :show do
    resources :plants, only: :create
  end

  resources :plants, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :name, presence: true
  validates :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def show
    @garden = Garden.find(params[:id])
    # We need @plant to be able to display the form on the page
    # as both the garden and the plant are needed
    @plant = Plant.new
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)

    # we can write the line below because a plant belongs to a garden
    @plant.garden = @garden

    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1 class="text-center"><%= @garden.name %></h1>

      <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12 mx-auto mt-5">
          <h4 class="text-white">Add a plant</h4>
          <%= simple_form_for([@garden, @plant]) do |f| %>
            <%= f.input :name, label_html: { class: 'text-white'} %>
            <%= f.input :image_url, label_html: { class: 'text-white'} %>
            <%= f.submit 'Add', class: "btn btn-success" %>
          <% end %>
        </div>

      </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @garden.plants.each do |plant| %>
      <div class="col-lg-4 col-md-6 col-sm-12 my-3 mx-auto">
        <div class="card-category mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>)">
          <%= plant.name.capitalize %>
          <%= link_to 'x', plant_path(plant),
            method: :delete,
            data: { confirm: 'Are you sure?'},
            class: 'card-remove-link'  %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardens533</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>